### ISSUE TITLE
Code is only on one CDN

### ISSUE THREAD

**Issue by chrillek** [sachinchoolur/lightGallery#1012]
## Summary

Although the documenttion ("Instalation") mentions three CDNs as source for the code, only one is actually offering it (jsdelivr). cdnjs only has version 1.10 and unpkg gives a 404

### Basic example
https://unpkg.com/browse/lightgallery@latest

### Motivation

Would be nice if one could use the same CDNs as with the prior version. Or if the documentation mentioned only the one CDN that works.

**Comment by sachinchoolur** [comment]
I think the issue is only with cdnjs - It might take some time to get [updated](https://github.com/snapappointments/bootstrap-select/issues/2083)

**UNPKG** works fine 
https://unpkg.com/lightgallery@2.0.1/lightgallery.umd.js
https://unpkg.com/lightgallery@2.0.1/plugins/autoplay/lg-autoplay.umd.js

**skypack**
https://cdn.skypack.dev/lightgallery@2.0.1
https://cdn.skypack.dev/lightgallery@2.0.0-beta.4/plugins/zoom

**jsdelivr**
https://www.jsdelivr.com/package/npm/lightgallery?version=2.0.1

**Comment by chrillek** [comment]
The link to unpkg in the documentation (and the Readme.md) is this one:
https://unpkg.com/browse/lightgallery@2.0.1
(notice the "browse" part!). That gives an 404 error.
Also, it might be helpful go give some indication as to what the different files _are_: umd vs. min in JavaScript (ok, I just figured out what umd stands for, but I'm not sure if I need this one or the min version) and in css lightgallery vs. lightgallery_bundle vs. lightgallery_core.
