### ISSUE TITLE
lightGallery crashes on iPhone/iPad > 50 images

### ISSUE THREAD

**Issue by yvesvdv** [sachinchoolur/lightGallery#102]
The plugin crashes when a gallery of about 50 images (each 50 - 100 kb) is shown.
e.g. http://www.c-life.be/nl/inbeeld/1-heistopdenberg/5-lentefestival-2015/

**Comment by boynet** [comment]
on what iphone?
sound like memory problem each image is taking some memory, I think there is some problem with your code as the lazyload not working, by looking the source code it look like all images are loaded in the slider.

another thing lightGallery maybe need a feature of virtual list, instead of keeping all the loaded images in the dom it should remove and insert again on demand

**Comment by yvesvdv** [comment]
Hi,

It was on an iPhone 4s.

Is lazyload a part of the lightgallery plugin or where can I find more info about this?

Thx for your help.

Yves


From: boynet
Reply-To: sachinchoolur/lightGallery
Date: donderdag 26 maart 2015 21:22
To: sachinchoolur/lightGallery
Cc: Yves Vander Veecken
Subject: Re: [lightGallery] lightGallery crashes on iPhone/iPad > 50 images (#102)


on what iphone?
sound like memory problem each image is taking some memory, I think there is some problem with your code as the lazyload not working, by looking the source code it look like all images are loaded in the slider.

another thing lightGallery maybe need a feature of virtual list, instead of keeping all the loaded images in the dom it should remove and insert again on demand

**Comment by sachinchoolur** [comment]
Hi,
I had tested lightGallery with more than 100 images on ipad and could not find any issue.
This might be because of insufficient memory. Any way there is an option for displaying low resolution images for mobile devices.
Create separate small resolution images for mobiles and put url inside  "data-responsive-src" attribute and set mobileSrc : true
 ex: 
``` html 
<ul id="lightGallery">
  <li data-src="img/img1.jpg" data-responsive-src="image/img-low-resolution1.jpg">
    <img src="img/thumb1.jpg" />
  </li>
  <li data-src="img/img2.jpg" data-responsive-src="image/img-low-resolution2.jpg">
    <img src="img/thumb2.jpg" />
  </li>
</ul>
```
``` javascript
$('#lightGallery').lightGallery({
    mobileSrc : true    
});
```


LightGallery does not load all images at a time. it depends on the preload setting.
if the 4th slide is active and preload is 1 then 3rd slide and 5th slide will be loaded in the background after the 4th slide is fully loaded.. if preload is 2 then 2nd 3rd 5th 6th slides will be loaded. 
You can check this with any browser  developer toolbar like firebug .

**Comment by jochienabuurs** [comment]
@sachinchoolur, @boynet is talking about the amount of images in the DOM. With 40 images and preload set to 1, when the slider loads, only the 2nd image will be fetched. When clicking next image (or swiping)  a few times  the images that are already shown stay in the DOM and thus take up memory. Would be better if preload also would remove/add images in the dom based on a virtual image list (js array with images or something)
