### ISSUE TITLE
How to add a custom button?

### ISSUE THREAD

**Issue by softshape** [sachinchoolur/lightGallery#1021]
We need to add "delete" button to the gallery. What is the recommended way to implement this?

**Comment by sachinchoolur** [comment]
Here is the demo - https://www.lightgalleryjs.com/demos/update-slides/

Let me know if you have any questions. The only trickiest part is, you need to update the thumbnails outside the lightGallery, once the delete operation is completed and lightGallery is closed

**Comment by softshape** [comment]
We're on React, will this jQuery example still work?

**Comment by sachinchoolur** [comment]
Yes, You can use [callbacks](https://www.lightgalleryjs.com/docs/react/#props-and-methods) instead of these events.

And what you see on the demo page is not actually jQuery. These are lightGallery [utilities](https://github.com/sachinchoolur/lightGallery/blob/master/src/lgQuery.ts) for dom manipulation.

These methods are attached to all main lightGallery dom elements. So you can directly access it as shown in the demo 

```js
function Gallery() {
    
    const onInit = useCallback((detail) => {
        const { instance } = detail;
        const addBtn =
            '<button type="button" aria-label="Add slide" class="lg-icon" id="lg-add"><svg>...</svg></button>';
        const deleteBtn =
            '<button type="button" aria-label="Remove slide" class="lg-icon" id="lg-delete"> <svg>...</svg></button>';

        // This will work without any additional library
        instance.outer.find('.lg-toolbar').append(deleteBtn);
        instance.outer.find('.lg-toolbar').append(addBtn);
    }, []);
    
    
    return (
        <div className="App">
            <LightGallery onInit={onInit}>
                <a href="img/img1.jpg">
                    <img alt=".." src="img/thumb1.jpg" />
                </a>
                ...
            </LightGallery>
        </div>
    );
}

```

I'll try to add a demo for react as well

let me know if you have any questions
