### ISSUE TITLE
Issue Generic type 'ɵɵFactoryDef' requires 1 type argument(s).

### ISSUE THREAD

**Issue by AmerQwaider** [sachinchoolur/lightGallery#1037]
anyone help me with this error
its happening while building the project after the installation

Angular CLI: 9.1.15
Node: 12.16.1

![issue](https://user-images.githubusercontent.com/55237841/120855325-fe706380-c586-11eb-90c5-0abdc197670b.png)

**Comment by sachinchoolur** [comment]
Hey @AmerQwaider ,

This doesn't look like a lightGallery issue. I found this link on stackoverflow - https://stackoverflow.com/questions/60898133/angular-9-ivy-generic-type-%C9%B5%C9%B5factorydef-requires-2-type-arguments

If you think this a lightGallery issue, please try to reproduce in a minimal project and share it with me. I'll try to resolve it ASAP

**Comment by AmerQwaider** [comment]
HI @sachinchoolur 

Tried to update the packages as in the article but no use, am not sure what to do

**Comment by dassmilytier** [comment]
Thanks for posting this. I ran into the same issue several days before and struggled to find a solution and also was afraid of posting the issue, because it might not be related to this library, also the errors point to it. At least I'm not the only one with this issue.

I'm using angular 12.0.3

what I tried by now:
- remove node_modules and npm install (npm ci)
- switch off ivy compiler in angular.json (even so this causes some other issues with ng12)
- tried to create a stackblitz for easier debugging. unfortunatly, I can not access the compiler log on stackblitz. However, the dev server is not starting up propperly, giving soe indication:  https://stackblitz.com/edit/angular-ivy-8ubtfb?
- I now created a github repo for sharing: https://github.com/dassmilytier/lightgallery-ng12-compiler-error
-- its a boilerplate project created via angular cli and only added the lightgallery via npm, added to the app.component
-- I also added a github action to build the master branch. If you look into the build, you can see the compiler errors.

I hope you can help. This issue was driving me mad for 2 days now.

**Comment by sachinchoolur** [comment]
Hey @dassmilytier,
Thanks for the demo. I'm able to reproduce the issue. I'll investigate and get back to you guys.

**Comment by sachinchoolur** [comment]
Hey @dassmilytier,

The issue has been fixed at least for angular 12. Please upgrade to lightgallery version `2.1.4-beta.0`

@AmerQwaider Which version of Angular do you use?

**Comment by dassmilytier** [comment]
Sry for the late reply... the compiler errors are gone with the provided beta version. thanks for your support. Still have to figure out some other lightgallery related issues, but the initial problem of this bug is gone.

thanks

**Comment by sachinchoolur** [comment]
Thanks for confirming. I'm creating separate builds for each angular version as it is creating issues with the older versions
If you see any lightGallery related issues, please create an issue. I'll try to help ASAP

**Comment by AmerQwaider** [comment]
@sachinchoolur 
apologize for the late reply... am using 
![image](https://user-images.githubusercontent.com/55237841/121919449-b1874c80-cd3f-11eb-8543-d9b0930e4134.png)

**Comment by sachinchoolur** [comment]
Hey @AmerQwaider ,

I've created a separate build for Angular 9.
Could you please upgrade to lightGallery version `2.2.0-beta.0` and import `LightgalleryModule` from `lightgallery/angular/9`

```js
import { LightgalleryModule } from 'lightgallery/angular/9';
```

Let me know if you face any issues

**Comment by AmerQwaider** [comment]
@sachinchoolur 

Great thanks will try it

**Comment by sachinchoolur** [comment]
Hope the issue is resolved
