### ISSUE TITLE
PLEASE STOP CHEATING DEVELOPERS!

### ISSUE THREAD

**Issue by Mister-Hope** [sachinchoolur/lightGallery#1048]
This project license is not related to GPLv3. REMOVE this line immedialy unless you want troubles.

https://github.com/sachinchoolur/lightGallery/blob/46eb69abd3847c9812843bfc9b9db6c6792b6101/package.json#L27

A GPLv3 project can allow other project to soft link it (e.g.: through npm ) and publish under other license (like MIT)

But your license is not a word with GPLv3. but basically:

- Free to use only in GPLv3 projects
- Otherwise pay you

That's definily not GPLv3, but a totaly commercial project that just open its source code.

A GPLv3 give right's under many other situation.

Edited: For anyone who waste time on it then find out payment is required:

![image](https://user-images.githubusercontent.com/33315834/121794511-59672200-cc3b-11eb-922e-27a424e15c7b.png)

![image](https://user-images.githubusercontent.com/33315834/121794516-697f0180-cc3b-11eb-98f2-15abbbf38b24.png)

Versions before May 25 is under MIT. please publish that as your own package and make changes you like.

If's totally ok make this project commercial, but unacceptable cheaking us it's a free project.

**Comment by DiemenDesign** [comment]
WOW, I can think of 100 different ways to word what you said in a manner that is neither condescending, or completely rude.

**Comment by Mister-Hope** [comment]
> WOW, I can think of 100 different ways to word what you said in a manner that is neither condescending, or completely rude.

It's nothing related to polite, license declarations should be aligned to the actually licnese, or it's a law problem.

**Comment by Mister-Hope** [comment]
> WOW, I can think of 100 different ways to word what you said in a manner that is neither condescending, or completely rude.

Also, I am glad if you can point out the actual problems in my words.

**Comment by DiemenDesign** [comment]
I didn't say what you were opening the issue for was incorrect, just that there's a better way to word things without being rude about it. If I was the devs of this repo, I would simply ignore your issue and close it, without commenting. What I'm saying, is that you are more likely to get your point across, and get more traction with them by not being rude about it. Just think, the person on the other side of the issue is a human as well.

**Comment by Mister-Hope** [comment]
The author has pushed me to great anger when I waste my whole morning on his project while believeing this project is GPLv3 as he decalred and then I found out I have to pay him to use it in my MIT project.

So I deserve it right? Is that what you mean?

I never push my anger to others when I am metting wrong docs, issues and so on. But this is about money.

Cheating others to pay to someone is a greate mistake and should be blamed under my culture.

**Comment by DiemenDesign** [comment]
Um, if the author has clearly stated what the license is, and you want to use it in another project with a different license, then that is not their issue, but yours.

On their website:
Open source license
If you are creating an open source application under a license compatible with the GNU GPL license v3, you may use this project under the terms of the GPLv3. Questions? Read the GPL FAQ.

They are not charging to use the Open Source version. They choose to use the GPL license for their own reasons. You will find however that the paid versions, uses a different license, a commercial license, and will most likely have features that the GPL version doesn't.

I also can't use it in my MIT License project, but you don't see me get all pissy about it.

If your going to get that upset about it, then you need to speak to Redhat and Fedora, because they do the same exact thing.

Also, just because a project is licensed as Open Source, does not mean it can't be a paid for product. I don't think you fully understand what Open Source is, in most cases it means FREE as in Freedom, not Free as in cost.

**Comment by DiemenDesign** [comment]
How about this one https://github.com/biati-digital/glightbox it's MIT licensed, and while it may not have all the features of lightGallery, it should allow you to use it in your project.

**Comment by Mister-Hope** [comment]
Thanks for the answer, I have other alternatives.

Just a other question, your answer just make me confused.

For a normal package on npm license with GPLv3(not this one, this one is sure more restricted). should any package requiring it (declaring it as deps) must be published base on GPLv3? Do you know that? Thanks!

I can find out many project doing this, but still on MIT.

**Comment by Mister-Hope** [comment]
Edited: this is sure not GPLv3, because GPLv3 do not force the situation of `use`

**Comment by DiemenDesign** [comment]
Their Open Source version uses the GPL, they are not doing anything wrong, but I can see where people (like yourself) can get confused. There's a lot of other projects doing the same thing. I don't like it much myself. But usually generally, GPL licensed dependencies are supposed to be used within projects with the same license. There are some, like MIT that can be used anywhere, which is why a lot of developer's prefer it, even myself.

My best guess as to why this project uses the GPLv3 specifically, is to to stop people using it in a manner that would circumvent the commercial license and it's usage. The top tier's of the commercial license allows use anywhere, but they require payment to do so, plus they are providing support.

They are still not doing anything wrong.

**Comment by Mister-Hope** [comment]
Thanks for the answer, but you do not clearly answer:
> For a normal package on npm license with GPLv3(not this one, this one is sure more restricted). should any package requiring it (declaring it as deps) must be published base on GPLv3? Do you know that? Thanks!

That's my biggest concern, and it seems that different area do have different results according to their own law?

**Comment by DiemenDesign** [comment]
GPLv3 should be used with other GPLv3 projects.

MIT can be used anywhere.

**Comment by Mister-Hope** [comment]
I decide to publish a historical version of this project in my own scope on npm and use it.  Thanks for your help again.

**Comment by Mister-Hope** [comment]
@DiemenDesign I just came with another curious throughts, since most package will use version rage to declare deps.

Do that means the author can charge to any projects publishing `lightgallery: ^2.0.0` which was ok before  under MIT?

**Comment by sachinchoolur** [comment]
Hey @Mister-Hope ,

I'm sorry if I wasted your time. Since 2016, the project was always under GPL v3 license. 

During a merge, the license file got renamed from LICENSE.MD to LICENSE. 
https://github.com/sachinchoolur/lightGallery/blob/9502efd57455b4353c0ecb0c890d023ed42caa91/LICENSE.md
I agree it was my mistake, but the license information was clearly stated on the documentation website and the readme.md as it is today. 

@DiemenDesign, Thank you so much for taking the time to respond to the comments and questions. I really appreciate that
