### ISSUE TITLE
thumbHeight instead of thumbWidth ?

### ISSUE THREAD

**Issue by smartcorestudio** [sachinchoolur/lightGallery#109]
Hi! Is there an option to set thumbHeight instead of thumbWidth? I had thumbnails with the same height but different widths. Something similar to the 2nd example ("Auto width") on this page: http://sachinchoolur.github.io/lightslider/examples.html So in default config it looks inaccurate. I've managed to get the result close to desired by setting:
```
#lg-gallery .thumb {
	width: auto !important;
}
```
Maybe there is a better way of doing this?

**Comment by sachinchoolur** [comment]
Hi,
If you are using animated thumbnails you have to specify thumbWidth in settings. By default thumbWidth is 100px. there is no way to use thumbheight instead of thumbWidth. because all the calculation for animated thumbnails depends on thumbWidth.
If you do not want to use animated thumbnails you can modify lightGallery.css however you want.
