### ISSUE TITLE
Icons are not always loaded

### ISSUE THREAD

**Issue by THEb0nny** [sachinchoolur/lightGallery#1091]
Icons in the interface are not always loaded. Instead of them, there are some signs.
How can this be solved?

**Comment by sachinchoolur** [comment]
Hey @THEb0nny,

I haven't experienced similar issues. But, in case if this keeps happening, you can try preloading the fonts or use your own icons instead of font icons.

You can also try using the version [2.2.0-beta.0](https://github.com/sachinchoolur/lightGallery/releases/tag/2.2.0-beta.0) which supports woff2


**preload fonts**

```html
<link
      rel="preload"
      as="font"
      href="https://www.lightgalleryjs.com/fonts/lg.ttf?io9a6k"
      type="font/ttf"
    />
```

Please re-open the issue if none of the above solutions working for you
