### ISSUE TITLE
Gallery crashes on iOS

### ISSUE THREAD

**Issue by Matt72** [sachinchoolur/lightGallery#114]
Hello,
It seems that on pages with larger number of photos the gallery keeps crashing on IOS.
This happens both on iPhone6Plus, IOS 8.3
and iPad IOS 8.3

I read something about a fix for this, but does not seem to work.
It works fine with about up to 20 photos.

After this it crashes as soon as I click a thumbnail.

**Comment by sachinchoolur** [comment]
Hi,
This is happening because phone is going out of memory when you use large number of high quality images.
Animation performance depends on image sizes too. so for ios lightGallery uses `left` property already instead of css3 `transform`.
You can try using law quality images for iphone by setting responsive-src. Please have a look at this link for more details https://github.com/sachinchoolur/lightGallery/issues/102#issuecomment-87253283

**Comment by Matt72** [comment]
Hi,
Thanks for your reply.
After trying different approaches I found a solution that works for me:
In LightGallery.js I have changed  useCSS: true tot  useCSS: false
No more crashes after this, even with quite a large number of thumbnails (>75)
