### ISSUE TITLE
Youtube autoplay not working.

### ISSUE THREAD

**Issue by ernestohegi** [sachinchoolur/lightGallery#1170]
## Description

When setting `autoplay` and `mute` on the Youtube configuration object, videos don't autoplay.

```js
lightGallery.default( 
        document.querySelector('.gallery'), 
        { 
          youTubePlayerParams: { 
            ...,
            autoplay: 1, 
            mute: 1 
          }
```

### Steps to reproduce

It seems this change https://github.com/sachinchoolur/lightGallery/blob/master/src/plugins/video/lg-video.ts#L201 prevents the `autoplay` functionality from working when setting it through the config. 

In previous versions the value of `autoplay` was dynamically set but now is hardcoded to `0`. 

It seems the  Youtube player fetches only the first value when two query params are set.

### Expected result

Youtube videos should autoplay when values `autoplay: 1`  and `mute: 1` are set through the `youTubePlayerParams` configuration object.

### Actual result

Youtube videos don't autoplay when the above mentioned values are set.

### Additional context

**Comment by sachinchoolur** [comment]
Hey @ernestohegi,

Autoplay might get blocked in some environments, such as IOS, Chrome 66+, and Safari 11+ if mute is disabled 
more info - https://developer.chrome.com/blog/autoplay/
https://stackoverflow.com/questions/40685142/youtube-autoplay-not-working


> In previous versions the value of autoplay was dynamically set but now is hardcoded to 0.
> 
> It seems the Youtube player fetches only the first value when two query params are set.

Yes, in version 2.x autoplay is managed using JS API not using query params. But it should not cause any issues.

**Comment by ernestohegi** [comment]
Thanks for your quick reply! 

The params passed through the `youTubePlayerParams` configuration object seem to be transformed into a query string that gets appended to the final Youtube iframe `src` value, but because `autoplay=0` is already set by default, `autoplay=1` doesn't have any effect.

Is there any other way to override the default `autoplay=0` value like it worked before?

**Comment by sachinchoolur** [comment]
Autoplay will not work even if you pass autoplay=1 in some environments due to their pre-defined auto-play policy.

If you want to override, you can use the version [2.3.0-beta](https://github.com/sachinchoolur/lightGallery/releases/tag/2.3.0-beta) and pass autoplay via URL params 

data-src="//www.youtube.com/watch?v=egyIeygdS_E&autoplay=1"

**Comment by johnmalib** [comment]
Since April 2018, Google made some changes to the  Autoplay Policy. You not only need to add the autoplay=1 as a query param, but also add allow='autoplay' as an iframe's attribute

So while [embed youtube](http://net-informations.com/q/mis/youtube.html) video, you will have to do something like this:

`<iframe src="https://www.youtube.com/embed/VIDEO_ID?autoplay=1" allow='autoplay'></iframe>`
