### ISSUE TITLE
Thumbnails aren't hidden on a mobile device

### ISSUE THREAD

**Issue by ozil07** [sachinchoolur/lightGallery#1309]
Hi!

with the toggleThumb option enabled on a mobile device, when changing a slide, a block with thumbnails pops up, I think this is not correct, everything is ok in a browser on a PC.

How can i this fix?

https://user-images.githubusercontent.com/19468008/169258909-f0bac691-6d68-4398-b366-1710686f41d9.mp4

**Comment by romka** [comment]
> This is only happening with non-animated thumbnails.
> I'll include the fix in the next version

Hi @sachinchoolur!

I use lightgallery version 2.7.1-beta.0 and it still has this issue on my Android device (on desktop it works as expected). I have the following settings:
```
allowMediaOverlap: true,
toggleThumb: true
```
If on a mobile device I tap on the "toggle thumbnail" button then thumbnails are hidden but as soon as I swipe to the next image in the gallery the thumbnails are shown again. It's not what I expect, I want the thumbnails to remain hidden. How can configure lightgallery so that it doesn't show thumbnails after swiping?
