### ISSUE TITLE
spacing between gallery images

### ISSUE THREAD

**Issue by elialombardi** [sachinchoolur/lightGallery#1333]
Is it possible to increase vertical and horizontal spacing between images in the gallery? (not the thumbnails after clicking an image)

**Comment by sachinchoolur** [comment]
Hey @elialombardi,

If you are not using [`zoomFromOrigin`](https://www.lightgalleryjs.com/docs/settings/#zoomFromOrigin) option, you can simply increase the padding of the `lg-img-wrap` div

```css
.lg-outer .lg-img-wrap {
    padding: 120px 0;
}
```

Otherwise, it is not possible at the moment as there are some calculations involved in finding the position of the image.

If it is a must for you, let me know. I'll suggest a workaround

**Comment by elialombardi** [comment]
Hi @sachinchoolur,
thanks for your reply.

Unfortunately, my issue is not with the gallery after I click on an image.

Instead, I refer to the images before clicking on the gallery:

![immagine](https://user-images.githubusercontent.com/7591419/177354236-1d1f8883-6315-4a59-a261-86ff1cbb1120.png)

I would like to have more space between them (horizontally and vertically).

Is this possible?

**Comment by elialombardi** [comment]
Nevermind, I used the following css:
`#lightgallery {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 10px;
}`
