### ISSUE TITLE
Please make it possible to start a Vimeo and YouTube video with sound

### ISSUE THREAD

**Issue by acwolff** [sachinchoolur/lightGallery#1378]
I investigated the Vimeo sound problem with  [this video test page](https://andrewolff.jalbum.net/TestVimeoYouTubeVideos_LG/), please do read the comment on rhat page to see the problem.

I did test the same videos wth lightGalley and two other Lightbox libraries. The lightGallery library is the only library where the sound in not automatically started.

So my request is: make it possible to start the video sound also automatically with the lightGalley library.

**Comment by acwolff** [comment]
On an iPad I see sometimes a Mute button.

**Comment by acwolff** [comment]
Reopened to show the same prblem with other libraries.

**Comment by acwolff** [comment]
I finaly found the unmute button on my PC: in the lower right corner next to the settings button!

**Comment by acwolff** [comment]
Reopened for a request.

**Comment by sachinchoolur** [comment]
From the [docs](https://www.lightgalleryjs.com/demos/video-gallery/#video-autoplay) - 

> Autoplay might be blocked in some environments, such as IOS, Chrome 66+, and Safari 11+ due to their predefined auto-play policy.
> 
> It is dependent on [many scenarios](https://developer.chrome.com/blog/autoplay/). By default, lightGallery mute the video and enable autoplay for the first slide if it contains videos. Since version 2.3.0, lightGallery allows you to pass query parameters via YouTube or Vimeo videos. If you want, you can unmute the video by passing ?mute=0 or ?muted=false respectively via video URL params
> 
> Also, [on IOS](https://stackoverflow.com/questions/43570460/html5-video-autoplay-on-iphone), you might need to set "playsinline": true, for HTML5 videos


You can control this behavior by passing `mute` parms 
But, please note that it might prevent the video autoplay

**Comment by acwolff** [comment]
THanks @sachinchoolur  for your  help:

I could unMute Vimeo videos with this code:

href="https://player.vimeo.com/video/74152497?muted=false" 

and for youTube:

href="https://www.youtube.com/embed/QbULyApj9Sw&mute=0"

**Comment by acwolff** [comment]
> > Also, [on IOS](https://stackoverflow.com/questions/43570460/html5-video-autoplay-on-iphone), you might need to set "playsinline": true, for HTML5 videos
> 
How should I do this?

I tried:

`video: '{"source": [{"src":"slides/IMG_1043.mp4", "type":"video/mp4"}], "attributes": {"controls": true, "playsinline": true}}',`

but this does not work.

**Comment by acwolff** [comment]
Setting "playsinline": true, does not remove the black page on an iPhone, as you can see in [my test album](https://andrewolff.jalbum.net/TestVimeoYouTubeVideos_LG/).

I think both the [fancyBox](https://andrewolff.jalbum.net/TestVimeoYouTubeVideos_FB/) and [photoSwipe](https://andrewolff.jalbum.net/TestVimeoYouTubeVideos_PS/) libraries do handle videos better and easier!

**Comment by Allmedialab** [comment]
Hi Sachin,

Unfortunately is this not working anymore:
href="https://player.vimeo.com/video/74152497?muted=false"
Vimeo starts without playing and muted sound.

Regards,
David

**Comment by itsmattsoria** [comment]
@sachinchoolur It looks like Vimeo may have updated things since you wrote lines 86-89 in the `lg-video-utils.ts` file:
```
    // For vimeo last params gets priority if duplicates found
    const vimeoPlayerParams = `?autoplay=0&muted=1${
        isPrivate ? `&h=${hash}` : ''
    }${defaultPlayerParams}${urlParams}`;
    return vimeoPlayerParams;
```
You noted that the last params get priority, but it seems like that's no longer the case, and instead is the other way around.

For example, here's a URL with `muted=1` appearing at the beginning of the URL params, and then `muted=0` appearing at the end, and it loads muted: https://player.vimeo.com/video/611997763?autoplay=0&muted=1&h=08456f3fa4&color=F6EC51&title=0&byline=0&portrait=0&muted=0
And if you swap the order, it loads unmuted: https://player.vimeo.com/video/611997763?autoplay=0&muted=0&h=08456f3fa4&color=F6EC51&title=0&byline=0&portrait=0&muted=1

Maybe that line can be rewritten to include the autoplay and muted params at the end?

```
var vimeoPlayerParams = (isPrivate ? "?h=" + hash : '?') + defaultPlayerParams + urlParams + "&autoplay=0&muted=1";
```

**Comment by jane-tif** [comment]
Looks like this is still an issue - the first parameter is taking precedence when parameters set to:
```
vimeoPlayerParams: {
   muted: false
},

```
URL is rendered as `//player.vimeo.com/video/0000000?autoplay=0&muted=1&muted=0`

In this case the video loads muted - would be great if this could be swapped so that the parameters set take over as suggested above.

**Comment by heythibault** [comment]
Yes the issue is still here. A future update maybe ?
