### ISSUE TITLE
Progressive loading of images

### ISSUE THREAD

**Issue by mas-iota** [sachinchoolur/lightGallery#1392]
## Summary

Hi there, we are at BuildFire.com one step away from purchasing the commercial license, our clients usually upload large images and the spinner is not favorable, we would like to show the image itself small sized maybe blurry until the src image is fully loaded, is that currently possible?

**Comment by sachinchoolur** [comment]
Hey @mas-iota,

Yes, it is already availbale. 

By default, lightGallery resizes the thumbnails and displays instead of the large image until the large image is fully loaded.

Note: this works only if you provide the original size of the large image via `data-lg-size` attribute

Docs- https://www.lightgalleryjs.com/docs/settings/#zoomFromOrigin
