### ISSUE TITLE
Is there a way to open custom html (my own code) in gallery?

### ISSUE THREAD

**Issue by Artsem77** [sachinchoolur/lightGallery#1430]
`<div class="popup-box" style="display: flex;">`
  `  <div class="img">`
   `      <img src="uploads/test.jpg" alt="" />`
`    </div>`
`    <div class="img-description">`
     `    <p>Lorem ipsum dolor</p>`
  `  </div>`
`</div>`

**Comment by jedifunk** [comment]
Is there a way to separate parts of the Caption?

I would like to have a Title in the toolbar (instead of the counter) and then a description below the image. I am using a react Lightbox right now for this, but want to eliminate react from my project (using Astro) and your vanilla JS solution is so close to being perfect for my needs.

See the attached image for my desired output
<img width="500" alt="Screen Shot 2022-12-08 at 4 00 00 PM" src="https://user-images.githubusercontent.com/369046/206453382-258cdd46-d58a-4602-bb68-84a74860399e.png">
