### ISSUE TITLE
Various galleries?

### ISSUE THREAD

**Issue by hubpork** [sachinchoolur/lightGallery#145]
Is it possible to run various lightbox galleries on one page?

**Comment by bibi-babi** [comment]
I can meet with my rustic code.
In true there are various ways php to create a sequence of elements.
In my case I did the following:
I created a variable ($ number_sequenze) give me the number sequence for each gallery (Gallery 1, Gallery 2, Gallery 3).
Then with a foreach for each gallery that you own (I had a custom field wordpress representing several galleries loaded), molds a UL with id "localVideo" + the number.
So everything is right at the end, is printed
<ul id = "localVideo1"> </ ul>
<ul id = "localVideo2"> </ ul>
<ul id = "localVideo3"> </ ul>

The problem is the JS code. In fact, he recalls one can UL.
so I made the options of the gallery as a function.
Then I recalled always with a foreach (for each tunnel) the various galleries with the same numerical sequence (1,2,3).
In this way it will be printed:
 boxVideo_lightGallery ('# localVideo1');
 boxVideo_lightGallery ('# localVideo2');
 boxVideo_lightGallery ('# localVideo3');


If you do not need an automation (eg do not know if you have 3 or 10 galleries), then create the code in a simple way:
UL each must have its specific ID (eg localVideo1), then the settings of the galleries all the same whether you use the single-function and calls for each ID of the UL
"Function boxVideo_lightGallery (id_boxvideo) {jQuery (id_boxvideo) .lightGallery (OPTION {})}"

<code>
<?php   
$box = 'video_box'; value of gallery (id or important value)

$number_sequenze = array ( '1','2','3');   $a=0;
foreach($box as $row){   ?> 
  <ul  id="localVideo<?php echo $number_sequenze[$a]; ?>" class="list-unstyled">  
  <li class="video-box videohtml-box"  data-src="http://videolink.it "    > 
  <a href="#"><img  class="image-box" src="image/image.jpg" /> </a> 
  </li>
</ul>
<?php }  ?>
 </code>


<code>
     <script type="text/javascript">
        function boxVideo_lightGallery(id_boxvideo){
           jQuery(id_boxvideo).lightGallery({ 
                preload:                      4, //number of preload slides. 
                showAfterLoad:           false,//Show Content once it is fully loaded
                thumbnail:                    false, //Whether to display a button to show thumbnails. 
                showThumbByDefault: false, //  Whether to display thumbnails by default.
                controls:                       false,   // If false, prev/next buttons will not be displayed.
                hideControlOnEnd:   true, //   If true, prev/next button will be hidden on first/last image.
                escKey:                     true, //Whether the LightGallery could be closed by pressing the "Esc" key.
                addClass:'localVideo',
            }); 
        }

jQuery(document).ready(function($){        
           <?php  $number_sequenze2 = array ( '1','2','3'); $b=0;

foreach($box as $row){ 
  boxVideo_lightGallery('#localVideo<?php echo $number_sequenze2[$b]?>'); <?php $b++; 
}   ?>
 });
        </script>

</code>

**Comment by hubpork** [comment]
Thanks Bibi...
It works with class and a data-ID.
