### ISSUE TITLE
Function request for 1.2 build

### ISSUE THREAD

**Issue by comtronix** [sachinchoolur/lightGallery#153]
can you build an extra view option? it would be nice to have an display window like the facebook comments output, but instead of the fb-comments i want to include a externall source. So i can inlude detailed information about the picture. The right column must be vertical scrollable for long content

**Comment by sachinchoolur** [comment]
Hi,
Did you see the http://sachinchoolur.github.io/lightGallery/demos/comment-box.html demo?
Instead of fb comments you can also add custom html including detailed information about the picture..

If you have any feature suggestion please post it in the [comment](http://sachinchoolur.github.io/lightGallery/#comments) section..

Thanks

**Comment by comtronix** [comment]
do you have an example of the code to use?
