### ISSUE TITLE
Using mouse wheel to change slide is broken on Firefox

### ISSUE THREAD

**Issue by vestaxpdx** [sachinchoolur/lightGallery#179]
Hi,

It seems using your mouse wheel to change slides is not working on the FireFox. 

In Chrome and IE it seems to work however it only goes forward slides no matter which way you scroll your mouse wheel. It would be cool if scrolling down went to the next slide and scrolling up went to the previous slide.

**Comment by sachinchoolur** [comment]
It works fine for me. which version of firefox do you use?

**Comment by vestaxpdx** [comment]
FireFox Version: 40.0.3 

I seem to get no errors in firebug either. :(

**Comment by sachinchoolur** [comment]
It works fine for me on firefox 40.0.3 .
If any issue is there that could be with [jQuery mouse wheel plugin](https://github.com/jquery/jquery-mousewheel). Because i have not written much code for [mouse wheel](https://github.com/sachinchoolur/lightGallery/blob/master/src/js/lightgallery.js#L1125) support.

**Comment by vestaxpdx** [comment]
Hmm, perhaps it's to do with how I have initiated the plugin as I am using `$('body').lightGallery({selector: '.lightgallery'});` not sure. I can see on your demos it works as expected fine.

I will try and do some debugging as to why it is not working for me.

**Comment by slantchev** [comment]
I have the same issue: the mouse wheel scrolls only forward irrespective of the direction of the wheel. I am using the lg-slide-circular for the transitions in case that matters.

**Comment by MarcosBL** [comment]
+1 came here for the same thing, only forward on mouse wheel

**Comment by MarcosBL** [comment]
I have faced also a related problem: LG scrolls the page in the background when you use the mousewheel up/down to move slides, and that shouldn't happen, as the user can feel a bit lost if he see something different in the page just after opening/closing the Gallery.

LG should lock the scroll while open, and release it again after closed.

You can attach your own onBeforeOpen & onBeforeClose events to fix this issue

````
var $window = $(window), previousScrollTop = 0, scrollLock = false;
$("#gallery").on('onBeforeOpen.lg',function(event){ scrollLock = true; });
$("#gallery").on('onBeforeClose.lg',function(event){ scrollLock = false; });
$window.scroll(function(event) {
    if(scrollLock) { $window.scrollTop(previousScrollTop); }
    previousScrollTop = $window.scrollTop();
});
````

But just in case you could be interested in adding this feature, here you have a working fiddle: http://jsfiddle.net/MarcosBL/4s9b3701/

**Comment by MarcosBL** [comment]
UPDATE: Funny, it works fine in demo @ http://sachinchoolur.github.io/lightGallery/demos/ - I'm also using "lg-slide-circular" just in case.

**Comment by vestaxpdx** [comment]
@marcosBL Awesome thanks for this fix!

**Comment by sachinchoolur** [comment]
I think you are missing the [jQuery mousewheel ](https://github.com/jquery/jquery-mousewheel) plugin.. (I forgot to mention in the docs also.. Sorry for that..)
It is required for cross browser support because javascript [mousewheel](https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel) and [DOMMouseScroll](https://developer.mozilla.org/en-US/docs/Web/Events/DOMMouseScroll) events are not standard yet..



@MarcosBL Thank you for time and effort.. I have also fixed the scrolling issue which you have mentioned..

**Comment by MarcosBL** [comment]
Thank you very much, reverted my changes and added jQuery mousewheel plugin: working like a charm !
