### ISSUE TITLE
Gallery controls hiding in firefox

### ISSUE THREAD

**Issue by sterrier** [sachinchoolur/lightGallery#199]
In firefox, I've noticed that the gallery controls don't hide as they are supposed to after the hideBarsDelay when you open an image and don't move the mouse. If you move the mouse and wait the hideBarsDelay it works.
Everything is fine for chrome or internet explorer.

**Comment by bibi-babi** [comment]
I have similar mistakes too
1) by clicking on the video thumbnail in the viewer on the whole page. the video does not change. Only with the right and left arrows can move.
2) controls youtube not displayed. but they are present because the mouse hover there is corresponding written.
3) perhaps autoplay is not working properly, because attivio stays on or off.

**Comment by bibi-babi** [comment]
For my problem (click on thumbnail on firefox and dont change image), i have solved with this option:
animateThumb: false

is set animateThumb false the problem  resolved.
bye

**Comment by sachinchoolur** [comment]
The issue has been fixed https://github.com/sachinchoolur/lightGallery/releases/tag/1.3.9
