### ISSUE TITLE
URL showing parameters

### ISSUE THREAD

**Issue by peaps** [sachinchoolur/lightGallery#206]
[In the demo on the main page](http://sachinchoolur.github.io/lightGallery/) you get #lg=1&slide=0 and similar in the URL when navigating the gallery.

However, in the demos on [the main demos page](http://sachinchoolur.github.io/lightGallery/demos/) you don't get this in the URL, which is cleaner and means you don't get lots of entries in the browser history.  Is there a way to get this behaviour in the latest releases?

**Comment by sachinchoolur** [comment]
Hi,
You need to include the hash plugin (lg-hash.js) in your document to get this feature..
In the [demo](http://sachinchoolur.github.io/lightGallery/demos/) it is not working just because i did not include hash plugin in the document..
http://sachinchoolur.github.io/lightGallery/docs/api.html#lg-hash
