### ISSUE TITLE
lightgallery is counting wrong images

### ISSUE THREAD

**Issue by Phoenix404** [sachinchoolur/lightGallery#261]
Hi everyone, I have a jsfiddle http://jsfiddle.net/jetnku0x/3/ when u click on an image then there will be open lightgallery and in my js array i have 5 imges and lightgallery shows 6 images. What  i have wrong done ?

**Comment by xeepress** [comment]
Possibly, the images that you don't want to is selected. It seems that there are other images somewhere in the nested tags.

**Comment by kursusHC** [comment]
Hi, 

Thanks for posting a well formatted question. You get a weird behavior because you're appending two elements for each image (`hiddenimages` and `displayimage`), why is that ? If you only use `displayimage` you get a correct behavior (btw be careful of the typo `dispalyimage`).

**Comment by Phoenix404** [comment]
In `displayImage` is cover of an album and this `displayimage ` contain html code for only one image and `hiddenimages` is variable of all images in `imagesarray` array and plus `hiddenimages` contain code of html and class that hide these images..
for e.g. `var hiddenimages += "<a href="+imagesarray[i]+"><img src="+imagesarray[i]+"></a>" ` and everytime  for loop loop hiddenimage get same code with new image as u see ..
**What i wanted to do ?**
I only wanted to display one  image as album cover.. and when user click  on this album cover it shows all images contained only on an container.. this container i did like this .. `var glrypost = "<span class="albumcont">+displayimage+" "+hiddenimages</span>"`.(btw in output these shows **undefined undefined** i dont know why ?).
`$(".gallery").append(glrypost);`

**Comment by kursusHC** [comment]
For your last question you wrote `dispalyimage` instead of `displayimage`.

It would be much easier to use the [dynamic mode](http://sachinchoolur.github.io/lightGallery/demos/dynamic.html) of Lightgallery so you don't have to struggle with HTML. Just fill an array with (at least) `src` and `thumb` and give it to the LG call.  This way gives a far more readable code :

```
<img id="cover1" src="http://lorempixel.com/100/100/sports/1/" />
<img id="cover2" src="http://lorempixel.com/100/100/food/1/" />
<div id="galery-container1"></div>
<div id="galery-container2"></div>
<script>
var album1 = [{
                "src": 'http://lorempixel.com/500/300/city/1',
                'thumb': 'http://lorempixel.com/100/100/city/1'
            }, {
                "src": 'http://lorempixel.com/500/300/city/2',
                'thumb': 'http://lorempixel.com/100/100/city/2'
            }, {
                "src": 'http://lorempixel.com/500/300/city/3',
                'thumb': 'http://lorempixel.com/100/100/city/3'
            }];
            

var album2 = [{
                "src": 'http://lorempixel.com/500/300/animals/1',
                'thumb': 'http://lorempixel.com/100/100/animals/1'
            }, {
                "src": 'http://lorempixel.com/500/300/animals/2',
                'thumb': 'http://lorempixel.com/100/100/animals/2'
            }, {
                "src": 'http://lorempixel.com/500/300/animals/3',
                'thumb': 'http://lorempixel.com/100/100/animals/3'
            }];
            
    $('#cover1').on('click', function() {
        $('#galery-container1').lightGallery({
            dynamic: true,
            dynamicEl: album1
        });
    });
    
    $('#cover2').on('click', function() {
        $('#galery-container2').lightGallery({
            dynamic: true,
            dynamicEl: album2
        });   
    });
</script>
```

[Working example here](https://jsfiddle.net/stt5n341/).

**Comment by Phoenix404** [comment]
Only last question, i would like to ask u is why it is counting wrong ? i did not understand what have u write in first comment. I am not very good in English so please explain me in poor words .. In your example u have  used dynamic mode, how can i create dynamic array with loop that contain same code as your ? your array is multidimensional array.

**Comment by kursusHC** [comment]
There is an `undefined` element at the end of `hiddenimages` because of `i<=imagesarray.length;` : `i` must be strictly inferior (<) to the length of your array, no inferior/equal (<=), because array index always start at 0, not 1. In your code it looks for `imagesarray[5]`, which does not exist, it is undefined, but the loop still adds HTML. 

Also there is an `undefined` that appears in the result window  because you did not declare your  `hiddenimages` variable as a string before using `+=`. Use `var hiddenimages = '';` instead of `var hiddenimages;`. 

Finally it is useless to define your `displayimage` every time in the loop. 

What I wanted to show you with my example is that the HTML your trying to inject (`<a class"hid" href...`) is useless, just let Lightgallery handle that with dynamic mode. By the way these are not multidimensional arrays, they are single arrays with a JS object inside.  You can fill it will any value you want.

**Comment by Phoenix404** [comment]
in my code has not '<='  it still give me match error..
**Uncaught TypeError: Cannot read property 'match' of undefined**
![cod](https://cloud.githubusercontent.com/assets/13603818/11900869/9a3ef72c-a5a8-11e5-8406-07c38296a416.png)
![error](https://cloud.githubusercontent.com/assets/13603818/11900870/9a5d2bd4-a5a8-11e5-886c-8be664ad5d20.png)
This is last time. 
Please please tell me what is wrong in my code ? and if possible please give small solution..

**Comment by kursusHC** [comment]
No image code please.

**Comment by Phoenix404** [comment]
sorry i dont understand. I show u images to explain my code .
i can not paste here, here i have jsfiddle where i pasted my code https://jsfiddle.net/ez1ud7mg/1/

**Comment by Phoenix404** [comment]
selector  does not work.
