### ISSUE TITLE
Close button issue

### ISSUE THREAD

**Issue by elemis** [sachinchoolur/lightGallery#297]
When working locally, the close button doesn't work in Chrome.

**Comment by kursusHC** [comment]
Hi, 

It does work. Do you have any JS error in console ?

**Comment by elemis** [comment]
I'm directly checking the demo in the lightgallery source package and the close button doesn't work on Chrome.

**Comment by kursusHC** [comment]
Since you didn't answer my question I've checked it myself, and there is indeed a JS error that prevent the gallery to work properly. This is because you opened the index file directly in the browser without using a webserver, and JS History API is disabled in Chrome when doing so, which triggers the error. Install a web server to "work locally'.

**Comment by abnersajr** [comment]
Exactly @kursusHC.
Just install some webserver and try again ;)
