### ISSUE TITLE
Hash plugin + dynamic option?

### ISSUE THREAD

**Issue by JaumeCardell** [sachinchoolur/lightGallery#302]
Does hash plugin work with dynamic option? The gallery is not opening automatically for me.

**Comment by kursusHC** [comment]
Hello, 

Yes this is supposed to work. Could you post a code example ? Thanks.

**Comment by JaumeCardell** [comment]
This is what I have for now:

```
jQuery(".js-showgallery").click(function() {
		var thisInstance = $(this);
		var endpoint = jQuery(this).data('endpoint');
		var id = jQuery(this).data('id');
		var anteriores = jQuery(this).data('anteriores');

		$.ajax({
			url: endpoint,
			method: 'GET',
			data: { id: id, anteriores:anteriores  },			
			success: function(response) {
				var json = JSON.parse(response);
				thisInstance.lightGallery({
					dynamic: true,
					thumbnail:true,
					dynamicEl: json
				});
			}
		});
	});
```

The json var equals:
```
[  
   {  
      "src":"intranet\/files\/25_02_1613_39_28LOS40DEAHORASONLOS30DEANTES3.jpg",
      "thumb":"intranet\/files\/25_02_1613_39_28LOS40DEAHORASONLOS30DEANTES3-100x100-771022a730bc5749.jpg"
   }
]
```

**Comment by kursusHC** [comment]
From your code I can't see how it is related to hash plugin. Does it work without it ? That said, the gallery should open. Do you have any error in console ?

**Comment by r1987** [comment]
I have the same question. But I think the problem is rather this, that how to fire the click event to open the specific dynamic gallery you'd want to see.

**Comment by maxvanloosbroek** [comment]
The specific slide doesn't open when you go to the hash link when using a dynamic lightgallery. Any updates on this?

**Comment by a1studmuffin** [comment]
I'm also interested to know if there's a good solution for this. Since dynamic galleries are created on click events rather than on page load, it makes sense that lightgallery can't open a hash URL for a dynamically created gallery without some extra work. I imagine it's probably solvable with some javascript on document load, but my monkey brain can't quite put two sticks together to reach the food at the moment.

**Comment by a1studmuffin** [comment]
Okay, my monkey brain seems to have figured it out. On my page I have a single gallery view with several category filter buttons (eg. "Ocean", "Landscape", "People" etc.). Clicking a button changes which images are visible using [isotope](http://isotope.metafizzy.co/). When someone clicks on an image, I create a dynamic gallery based on which images are currently visible. I use the category as the galleryId, eg. "show all" is 0, "ocean" is 1, "landscape" is 2 etc. Since dynamic galleries aren't created at the time the page loads, you need a bit of javascript in your own code to display the gallery instead. At the end of my `$(window).load` function I've added this - you'll need to adapt to your specific site of course:

```
    // adapted from http://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript
    function getParameterByName(name, url) {
        if (!url) url = window.location.href;
        name = name.replace(/[\[\]]/g, "\\$&");
        var regex = new RegExp("[?&#]" + name + "(=([^&#]*)|&|#|$)"),
            results = regex.exec(url);
        if (!results) return null;
        if (!results[2]) return '';
        return decodeURIComponent(results[2].replace(/\+/g, " "));
    }

    // lightgallery dynamic hash support: if url ends with "#lg=X?slide=Y", lets jump to the correct category filter by clicking the category button, and also optionally view the specified slide
    var galleryIndexParam = parseInt(getParameterByName('lg'));
    if (!isNaN(galleryIndexParam))
    {
        console.log('Setting gallery index to ' + galleryIndexParam);
        // Click on the desired category filter button, which will update the isotope layout and hide a bunch of images by adding the 'isotope-hidden' class
        $( "#options .option-set" ).children()[galleryIndexParam].click();

        // Now check if a slide id was in the URL, if so, try and display that slide
        var gallerySlideParam = parseInt(getParameterByName('slide'));
        if (!isNaN(gallerySlideParam))
        {
            console.log('Setting gallery slide to ' + gallerySlideParam);
            // Click on the desired slide
            $container.children('.element').not('.isotope-hidden')[gallerySlideParam].click();
        }
    }
```
The image click() function is what creates the dynamic gallery. It works a treat, though I've discovered a [separate bug](https://github.com/sachinchoolur/lightGallery/issues/387) when a gallery hash URL is loaded in a fresh tab. But I can live with that for now.
