### ISSUE TITLE
Dynamic mode: Incorrect image is loading when clicked

### ISSUE THREAD

**Issue by benjipnz** [sachinchoolur/lightGallery#305]
I've finally managed to get things working as I wanted them, however a new issue has arisen.

When I set up my lightGallery dynamically, and use 'index' to target which image should open when a link is clicked, the wrong image shows up unless it's the very first click.

In other words, if you initially click on a thumbnail image, you'll see the correct larger image being selected in the gallery that pops up. However, if you then close that image, and click on a different thumbnail image, you will see the wrong image being enlarged (it's grabbing the first one that you clicked on). I figure that this must be something to do with the 'index' functionality getting stuck after the first click?

I've created a jsfiddle that demonstrates the issue (apologies for all the nested DIVs etc., however I'm confident that those are not the cause): http://jsfiddle.net/fcdeLd03/18/

Anyone have any ideas?

**Comment by szymekz** [comment]
I have the same problem. I tried editing everything and no luck...

**Comment by nebrot** [comment]
Have you tried the slide-method? http://sachinchoolur.github.io/lightGallery/docs/api.html#methods ?

**Comment by szymekz** [comment]
That's something new, but also a new error: Uncaught TypeError: this.$outer.find is not a function

**Comment by nebrot** [comment]
See #254, perhaps there is a solution for you.

**Comment by szymekz** [comment]
So, I found my mistake... Problem solved when I used parseInt() on number that I passed to lightGallery as index:
` $(this).lightGallery({
        dynamic: true,
        thumbs: true,
        hash:false,
        index: parseInt(slideNum), 
        preload: 3,`

**Comment by azerafati** [comment]
I am facing this issue too and even `parseInt` didn't fixed it.  @szymekz  Are you sure that fixed it for you? didn't you made any other change?

**Comment by szymekz** [comment]
I'm sure! I remember the way to this solution was replacing variable that
contained my slide number with actual number, so I knew something was wrong
with variable. Try <code>index: 3</code> for example and see if that is
working correctly.


02.02.2017 07:55 "Alireza Zerafati" <notifications@github.com> napisał(a):

**Comment by sachinchoolur** [comment]
Hi Guys,
Index field requires a number. that is why you pass a string, it picks the wrong slide. Ideally using parseInt should fix the issue.

@azerafati please provide a jsfiddle demo. I'll try to help you

**Comment by henriquesobral** [comment]
Basically this problem occurs because the index is used only when lightGallery is instantiated for the first time. After that it's call the method init() over already a instantiated lightGallery object, found at element's data attribute.

```javascript
$.fn.lightGallery = function(options) {
    return this.each(function() {
        if (!$.data(this, 'lightGallery')) {
            $.data(this, 'lightGallery', new Plugin(this, options));
        } else {
            try {
                $(this).data('lightGallery').init();
            } catch (err) {
                console.error('lightGallery has not initiated properly');
            }
        }
    });
};
```

The ```options``` argument (where our index is), is used only when instantiates a new lightGallery object
```javascript
$.data(this, 'lightGallery', new Plugin(this, options));
```

After instantiated, it only calls ```init()``` method without our ```options```.
```javascript
$(this).data('lightGallery').init();
```

https://github.com/sachinchoolur/lightGallery/blob/master/src/js/lightgallery.js#L1326

**Comment by basticom-internet** [comment]
After experiencing the same issues I ended up wrapping the `.slide()` function inside an `onAfterOpen.lg` event. So instead of trying to reInit the lightGallery using the `index` parameter, I load the requested slide using my `$occasionsLightGallerySlide` variable, like so:

```
if ( !$occasionsLightGallery.data('lightGallery') ) {

	console.log("Creating new lightGallery instance");

	// $occasionsLightGallerySlide contains an integer that corresponds with the current slide that we want to load

	$occasionsLightGallery.lightGallery(
		{
			index : $occasionsLightGallerySlide,
			preload : 1,
			cssEasing : 'cubic-bezier(0.25, 0, 0.25, 1)',
			download : false,
	       		dynamic : true,
			fullScreen : false,
	       		dynamicEl : jQuery( '.slick-zoom' ).data( 'images' ),
	 	}
	);

} else {

	console.log( "Using existing lightGallery instance");

	$occasionsLightGallery.lightGallery();

	$occasionsLightGallery.on(
		'onAfterOpen.lg',
		function( event ) {
			$occasionsLightGallery.data('lightGallery').slide( $occasionsLightGallerySlide );
		}
	);

}
```

This solution checks if the lightGallery is initiated and runs the initial configuration (using the `index : value`). When the lightGallery is already initialized, it simply fires up the gallery and loads the current slide using the `onAfterOpen.lg` hook.

Perhaps this can be useful for someone having the same problem(s).
