### ISSUE TITLE
Videos and Images in the same gallery

### ISSUE THREAD

**Issue by joaomarcosfg** [sachinchoolur/lightGallery#309]
Hello!

Is it possible to have videos and images in the same gallery?

Thanks for any help!

**Comment by ajoah** [comment]
Yes, absolutely.

**Comment by joaomarcosfg** [comment]
Do you have an example, @ajoah ? Causa I could not make it work. I need to have vimeo, youtube and imagens in the same gallery.

Thanks for any help! 

Best Regards,

**Comment by kursusHC** [comment]
@joaomarcosfg please post a fiddle with what you have so far.

**Comment by BlackSmithPL** [comment]
Hello!
I've got similar question. The thing is that I would like to have photos and HTML5 videos in one gallery. And the problem is that gallery with HTML5 videos is built by "ul" and "li" tags (http://sachinchoolur.github.io/lightGallery/demos/html5-videos.html), not "a" tags, like gallery of photos.
Is it possible to put it in one gallery somehow?
Thanks for any help

**Comment by ajoah** [comment]
@BlackSmithPL : you can use the tags you want : http://sachinchoolur.github.io/lightGallery/demos/html-markup.html
@joaomarcosfg: you can see a real example [here](https://web.archive.org/web/20160530190341/http://www.chausson-motorhomes.com/gamme/lowprofile/)  (below "Have a look at our line")

**Comment by BlackSmithPL** [comment]
Thanks a lot!
