### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by jksenthilraja** [sachinchoolur/lightGallery#433]
I am developing angularjs project
I getting images  from localhost and I use data-src also but i got this error in 

   Cannot read property 'match' of undefined  **lightgallery-all.min.js:4**

**Comment by abnersajr** [comment]
Please provide more info like a fiddle, your angular structure something like this.

**Comment by jksenthilraja** [comment]
Ok **bro** that one I fixed but now  what is  problem'na I change width of div then stay the position of images 
**eg:** Initially div size **80%** after click button then reduce width **50%** (do not reduce whole browser size) then didn't arrange  gallery stay on old structure. So what I use'na  when click button then change **order BY: ascending or descending**  but this is wrong way any other solution you have?

**Comment by lapDog** [comment]
how to fix it?

**Comment by sachinchoolur** [comment]
Hi @jksenthilraja,
Sorry for not responding to your query. Hope you fixed it.

@lapDog, 
I think the issue is because of the wrong markup you have. You can fix the issue by using selector property.
More info - http://sachinchoolur.github.io/lightGallery/demos/html-markup.html

Please provide a jsFIddle demo if the issue persists.
