### ISSUE TITLE
Zoom question

### ISSUE THREAD

**Issue by stephenycchang** [sachinchoolur/lightGallery#448]
I've included the lg-zoom along with lightgallery along with the standard jQuery.

The code I'm using is 

```
<div id="lightgallery">
    <a href="url" class="img-selector">
        <img src="url" />
    </a>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("#lightgallery").lightGallery({
            selector: ".img-selector",
            zoom: true,
            download: false,
            enableTouch: true
        });
    });
</script>
```

Everything works as expected, however, when clicking zoom twice, the zoom starts zooming in the bottom right corner of the page. I do not get any errors etc.

**Comment by crux153** [comment]
I've also been experiencing this issue and figured out the problem.

Since jQuery 3.0, .width() uses getBoundingClientRect() instead of offsetWidth (same applies for .height()). While offsetWidth returns the width before applying css transform(), getBoundingClientRect() returns the real width of image after applying css transform(). Therefore, lightGallery wasn't able to fix the offset after zooming.

I fixed this issue by replacing .width() and .height() with .prop("offsetWidth") and .prop("offsetHeight") inside the zoom function of lg-zoom.js line 69-97.


```
/**
 * @desc Image zoom
 * Translate the wrap and scale the image to get better user experience
 *
 * @param {String} scaleVal - Zoom decrement/increment value
 */
var zoom = function(scaleVal) {

    var $image = _this.core.$outer.find('.lg-current .lg-image');
    var _x;
    var _y;

    // Find offset manually to avoid issue after zoom
    var offsetX = ($(window).width() - $image.prop("offsetWidth")) / 2;
    var offsetY = (($(window).height() - $image.prop("offsetHeight")) / 2) + $(window).scrollTop();

    _x = _this.pageX - offsetX;
    _y = _this.pageY - offsetY;

    var x = (scaleVal - 1) * (_x);
    var y = (scaleVal - 1) * (_y);

    $image.css('transform', 'scale3d(' + scaleVal + ', ' + scaleVal + ', 1)').attr('data-scale', scaleVal);

    $image.parent().css({
        left: -x + 'px',
        top: -y + 'px'
    }).attr('data-x', x).attr('data-y', y);
};
```

**Comment by stephenycchang** [comment]
Thanks @crux153 . This works great.

Perhaps a pull request?

**Comment by abnersajr** [comment]
I will check this issue today to see if we have a final solution.

**Comment by stephenycchang** [comment]
@abnersajr , thanks! Any updates?

**Comment by sachinchoolur** [comment]
Hi Guys,
Please use the latest version of lg-zoom.js. It is now jQuery 3.0 compactible.

Thanks :)
