### ISSUE TITLE
lg-Share not showing thumbnail on facebook or correct thumbnail on facebook

### ISSUE THREAD

**Issue by simran2017** [sachinchoolur/lightGallery#484]
we try to share the image with default option it always show the first image which is in the gallery as thumbnail. Let us say i am sharing the 5th image on the page on Facebook on Facebook it always shows the first image as thumbnail on Facebook. Do we have to make any changes so that correct thumbnail shows on Facebook when we share it. another example is from http://sachinchoolur.github.io/lightGallery/demos/share.html in this case if we share image on Facebook it doesn't show anything on Facebook as thumbnail. CAn you share some documentation or how we can result the issue.

**Comment by sachinchoolur** [comment]
Hi 
It's because Facebook is not considering # as a part of the URL.
The solution is to create dedicated pages for each of your images and pass the url it via lightGallery  data-facebook-share-url. 

These pages should contain your image and its description.
``` html
<meta property="og:image" content="your-image.jpg" />
```
Please refer the following post for more info
https://www.facebook.com/help/community/question/?id=10200814000150949
