### ISSUE TITLE
captions that start with a dot cause lightgallery to crash

### ISSUE THREAD

**Issue by yacoob** [sachinchoolur/lightGallery#516]
[Here](http://jsfiddle.net/yacoob/g0dghhmv/8/) is an example of this. As you can see, second image's caption starts with a dot, and as a result causes this crash:

```
Uncaught Error: Syntax error, unrecognized expression: ...and swords
    at Function.Sizzle.error (http://code.jquery.com/jquery-1.11.0.js:1471:8)
    at tokenize (http://code.jquery.com/jquery-1.11.0.js:2085:11)
    at select (http://code.jquery.com/jquery-1.11.0.js:2473:11)
    at Function.Sizzle [as find] (http://code.jquery.com/jquery-1.11.0.js:880:9)
    at jQuery.fn.init.find (http://code.jquery.com/jquery-1.11.0.js:2684:11)
    at jQuery.fn.init (http://code.jquery.com/jquery-1.11.0.js:2801:38)
    at jQuery (http://code.jquery.com/jquery-1.11.0.js:75:10)
    at Plugin.addHtml (http://sachinchoolur.github.io/lightGallery/lightgallery/js/lightgallery.js:485:35)
    at http://sachinchoolur.github.io/lightGallery/lightgallery/js/lightgallery.js:787:27
```

This is caused by the fact that `Plugin.addHtml` checks the first character and tries to interpret the string as jquery selector if that character is `.` or `#`. 

Quick workaround is to start your caption with a space, but it should really not behave this way :)

**Comment by sachinchoolur** [comment]
Hi @yacoob,
Sorry, the documentation for `data-sub-html` attribute was not very clear. I've updated it
This happens only when `data-sub-html` is not available. In that case, as a fallback captions are fetched from `alt` or `title`. If you are using `data-sub-html` you can easily wrap your caption with a `<span>` tag to avoid the issue 

Here is the updated demo http://jsfiddle.net/g0dghhmv/9/
Related to : https://github.com/sachinchoolur/lightGallery/issues/509

I think it is a very rare scenario and we have a few ways to solve the problem.

**Comment by soswow** [comment]
I am glad this issue exists because I was planning on reporting it.
the bigger problem is that you folks has an example code over here https://www.lightgalleryjs.com/docs/react/ as
```
<a href="img/img1.jpg">
    <img alt=".." src="img/thumb1.jpg" />
</a>
<a href="img/img2.jpg">
    <img alt=".." src="img/thumb2.jpg" />
</a>
```
Now imagine my frustration when I first time installed it, copy-pasted your example, replaced image `src` with proper images and found it doesn't work. It was very frustrating, since your example, https://stackblitz.com/edit/lightgallery-react?file=index.tsx is as limited as it can be and very close to what I had but mine doesn't work. After some time of debugging, I found it. 

I suggest you change your example and get rid of dots from `alt` by default.

**Comment by sachinchoolur** [comment]
I completely forgot about this. Updated the docs
