### ISSUE TITLE
Toggle Facebook comment box

### ISSUE THREAD

**Issue by neoman666** [sachinchoolur/lightGallery#562]
Hi, how can I show and hide the facebook comment box by a button similar to this example?

https://www.jmbelloteau.com/photos/underwater/fishes/#lg=1&slide=16

Thanks

**Comment by sachinchoolur** [comment]
Hi @neoman666,
Actually, this is lightGallery plugin developed by @jmbelloteau. He has already shared his code, but i did not get time to implement that :disappointed:

Please send me an email at sachi77n@gmail.com. I'll send you the code.

**Comment by jmbelloteau** [comment]
Come on @sachinchoolur, it's been a while now... stop procrastinate on this 🤓  !

**Comment by sachinchoolur** [comment]
I'm really sorry for the delay. I'll try to include it in version 1.4.

**Comment by neoman666** [comment]
Ok, I wait for the version 1.4... Thanks

**Comment by jmbelloteau** [comment]
@sachinchoolur was kidding man, but ok 😄  !

**Comment by jimblue** [comment]
Hi @neoman666 !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please guy change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

**Comment by jimblue** [comment]
Hi @neoman666 !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

**Comment by jimblue** [comment]
Hi @neoman666 !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers
