### ISSUE TITLE
Youtube automatic thumbnails

### ISSUE THREAD

**Issue by djmtype** [sachinchoolur/lightGallery#585]
Trying to automatically pull in poster images from Youtube seems to be failing here. There are no errors. Videos play, but there are no poster images loading. What am I doing wrong?

```
<script type="text/javascript" src="js/vendor/lightgallery.js"></script>
<script src="js/vendor/lg-thumbnail.min.js"></script>
<script src="js/vendor/lg-video.min.js"></script>
```

Plus, I've also included lightgallery's css files. 

```
// js
$('#video-thumbnails').lightGallery({
    loadYoutubeThumbnail: true,
    youtubeThumbSize: 'default',
    loadVimeoThumbnail: true,
    vimeoThumbSize: 'thumbnail_medium',
}); 
```

```
// html
<ul id="video-thumbnails" class="list-unstyled row">
<li class="col-xs-6 col-sm-4 col-md-3 video" data-src="https://www.youtube.com/watch?v=meBbDqAXago">
</li>
<li class="col-xs-6 col-sm-4 col-md-3 video" data-src="https://www.youtube.com/watch?v=Pq9yPrLWMyU">
</li>
<li class="col-xs-6 col-sm-4 col-md-3 video" data-src="https://vimeo.com/1084537">
</li>
<li class="col-xs-6 col-sm-4 col-md-3 video" data-src="https://vimeo.com/35451452">
</li>
</ul>
```

**Comment by sachinchoolur** [comment]
Hey @djmtype ,
Sorry for not being clear about youtube thumbnails and posters.
lightGallery does not load poster images from youtube because at the max youtube is providing 480*360 images. But still, if you want to load poster form youtube, you can simply pass the image url via `data-poster` attribute.

``` html
<div id="video-gallery">
  <a href="https://www.youtube.com/watch?v=meBbDqAXago" data-poster="https://img.youtube.com/vi/meBbDqAXago/0.jpg" >
      <img src="img/thumb1.jpg" />
  </a>
  ...
</div>
```
In case of thumbnails, If `loadYoutubeThumbnail` is enabled, lightGallery automatically load thumbnails from YouTube. (Thumbnails you see on the bottom panael when lightGallery is opened) 
Hope that is clear. Let me knoe if you have ny other queries
