### ISSUE TITLE
Video not working in anchor mode

### ISSUE THREAD

**Issue by AminulBD** [sachinchoolur/lightGallery#609]
Hello,

Thanks for the nice plugin. I'm trying to add video in single anchor mode but it's not working. Can you please check this pen: https://codepen.io/aminul/pen/KqMXZw

I'm getting error: "lg-video.js:87 Uncaught TypeError: Cannot read property 'play' of undefined"

Can you please help me to fix this issue?

Thank you again.

**Comment by sachinchoolur** [comment]
Hey @AminulBD,
``` html
<a id="bipYOi" href="" data-poster="https://sachinchoolur.github.io/lightGallery/static/img/videos/h-video1-poster.jpg" data-sub-html="<h4>CGI Animated Short HD: Student Academy Award Winning 'PeckPocketed' by Kevin Herron</h4>" data-html="#video1">
		Play
</a>
```
You just need to remove the `#` from `href` attribute. href is considered as a fallback for data-src in lightGallery. When you use html5 videos `data-src` should not be provided. Since you are using anchor tag as a selector, you should not provide `href` property as well. 

Sorry for not being clear about this. I'll update the documentation ASAP. Here is the updated codepen demo https://codepen.io/anon/pen/awmvjj

**Comment by AminulBD** [comment]
Thank you @sachinchoolur for the fast solution. 💯 👍
