### ISSUE TITLE
Blurry images when gallery first opened on Android

### ISSUE THREAD

**Issue by chrisdeeming** [sachinchoolur/lightGallery#762]
Hi @sachinchoolur 

We've had some users report blurry images on Android devices when the gallery is first opened:

![image](https://user-images.githubusercontent.com/2158514/37218353-19d1103a-23b8-11e8-9fad-3f97e7cfe5a6.png)

We asked the user to reproduce the problem on your own demo site too:

![image](https://user-images.githubusercontent.com/2158514/37218401-346ecc3e-23b8-11e8-9d14-32fe7316ea31.png)

After zooming in, and back out, the image corrects itself:

![image](https://user-images.githubusercontent.com/2158514/37218422-44fee796-23b8-11e8-9539-93bf910db1a2.png)

This is using the latest LightGallery release.

Many thanks.

**Comment by sachinchoolur** [comment]
In the demo page we are using progressive images. You will see the blurry images until it gets fully loaded . Could you please prove your website URL. I'll check the issue and get back to you

**Comment by chrisdeeming** [comment]
Hi @sachinchoolur 

The only URL you need is your own. Those images are fully loaded, and they'd stay like that regardless of how long you wait. The only way to get them to display correctly is to zoom into and zoom out of the image.

The user tells me that it can be intermittent and I've been told that it is Android 8 they've tested on.

**Comment by sachinchoolur** [comment]
Okay. I'll check and get back to you. Thank you for pointing this out.

**Comment by steffenweber** [comment]
May I ask what the status of this issue is?

There seems to be a related issue on iOS / Mobile Safari where image rendering is interrupted prematurely, too (the result here isn't a blurry but a cropped image). This issue also only exists "when the gallery is first opened". It disappears after swiping to other images and back again.

![2018-07-30_112944-fs8](https://user-images.githubusercontent.com/1138129/43391101-0bbc49d0-93f0-11e8-9a4a-4491b538aa25.png)
