### ISSUE TITLE
Question : import lightGallery with Webpack Encore

### ISSUE THREAD

**Issue by joelisayas** [sachinchoolur/lightGallery#888]
Hi,

i'm trying to import in a js file the plugin like this :
```javascript
import 'lightgallery/dist/js/lightgallery-all';

$(function() {
     $("#lightgallery").lightGallery();
});
```

but i got this error:  jquery.js: Uncaught TypeError: $(...).lightGallery is not a function

Any advice ?

> 

>

**Comment by Sogl** [comment]
I have the same problem. 
@sachinchoolur Please help.

**Comment by stof** [comment]
could it be possible that you have 2 different jquery versions in your project, one in the dependencies of your own code, and another one in the dependencies of lightgallery ?

lightgallery should be using a peerDependency for jQuery as it registers a plugin on jQuery (and so expects to receive the jQuery package used by the parent), but it does not properly do it. So things will work only if jQuery is hoisted due to using the same version.
