### ISSUE TITLE
How does lightgallery continue?

### ISSUE THREAD

**Issue by neoman666** [sachinchoolur/lightGallery#923]
The last update was over 1 year ago. I now ask myself whether the project is dead and whether I should look for an alternative?

Does anyone know of a comparable alternative to light gallery?

**Comment by Novezeil** [comment]
Wondering the same. Looks like this project is discontinued so no longer to bother purchasing a commercial license.

As down to lightbox choices, it's basically either Fancybox, lity or PhotoSwipe. License aside,

* Fancybox is able to serve as a drop-in replacement against lg (in my case, I was using fancybox but looking for using lg to replace it but turns out project is dead). 
* Lity is free & lightweight with barebone features.
* Photoswipe is promising but configuration can end up in hell.

All 3 above don't provide easy access to comment section which is a shame, but in comparison I would stick with fancybox (least it's still updating).

There's another alternative called Modulobox, UI seems great but also haven't been updated in the past year or so, so presumably dead in terms of updating. Also this is neither free nor open-source, so won't bother to try at first place.

**Comment by sachinchoolur** [comment]
Apologize for the inconvenience.
I was not able to provide support due to some personal reasons for some time.
But now things are stored put from my end and will be able to provide support and continue developing the plugin.

Thank you for understanding :)
