### ISSUE TITLE
Thumbnail on click slow to render

### ISSUE THREAD

**Issue by Vanlon** [sachinchoolur/lightGallery#968]
I'm working on light gallery where I click the image thumbnail and it opens the gallery.  It's inside of a filtered page so I can't put it in the document ready function.  Works fine without the trigger click event, but I have to double click it then.  Hoping someone can help me streamline this.

I've created it in [jsfiddle](https://jsfiddle.net/9Ld8ac36/1/)

var $lg = $('#pictures .picture');

$lg.on("click", function(e) {

  e.preventDefault();

  $lg.lightGallery();
  $lg.on('onBeforeClose.lg',function(event, index, fromTouch, fromThumb){
						try{$lg.data('lightGallery').destroy(true);}catch(ex){};
					});

  $('.picture').trigger("click");
});

**Comment by sachinchoolur** [comment]
Hey @Vanlon ,
You don't have to implement your own click function as lightGallery does this automatically.
https://jsfiddle.net/ne7jvz98/

I think I'm missing something here. Could you please elaborate a little more on the filter part? 
If you are using client-side filtering, you just need to destroy and re-initiate the gallery once the filter is completed.

Demo - https://sachinchoolur.github.io/lightGallery/demos/methods.html

Or in case if you need to implement your own click function, please consider using the dynamic mode. 
Note: Apply the click function on the thumbnails and pass the index of the thumbnails, so that the gallery stars with the clicked thumbnails 

https://sachinchoolur.github.io/lightGallery/demos/dynamic.html

Please let me know if you have any questions

**Comment by Vanlon** [comment]
Hi, what I mean by filter is there is a list box and the light gallery is inside of a pictures tab below.  New item in the list new, images and doesn't refresh the page.  Having trouble initiating it after filter which is why I went this route.  I'll give your suggestions a try.  Thank you.

**Comment by sachinchoolur** [comment]
Oh, I see. Then you need to initialize the Gallery once the tab is opened.

If you can post the code to open the tab which contains lightGallery, I'll try to provide a solution
